name: Update submodules and deploy

on:
  repository_dispatch:
    types: [submodule-update]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PARENT_REPO_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote --checkout
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git add .
          git diff --staged --quiet || git commit -m "chore: update submodules"
          git push https://x-access-token:${{ secrets.PARENT_REPO_TOKEN }}@github.com/eliott-colin/musicdle-docker.git

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /srv/projects/musicdle
            git pull
            git submodule update --remote --checkout
            cd /srv
            docker compose up -d --build musicdle-front musicdle-back